import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import { Navbar } from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen`}
        >
          <div className="flex flex-col">
            <header className="bg-white shadow">
              <div className="max-w-full mx-auto py-4 px-6 sm:px-6 lg:px-6 flex justify-between items-center">
                <h1 className="text-2xl font-bold text-gray-900">FOOD</h1>
                <SignedIn>
                  <UserButton showName />
                </SignedIn>
              </div>
            </header>
            <div className="flex">
              <Navbar />
              <div className="w-full h-full">{children}</div>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
