"""expiry table added

Revision ID: 8b5e2c6fccf9
Revises: 6e0d8155d4ac
Create Date: 2025-01-10 02:08:36.492529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b5e2c6fccf9'
down_revision: Union[str, None] = '6e0d8155d4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expiry',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('days_remaining', sa.Integer(), nullable=False),
    sa.Column('date_added', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory.batch_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.p_id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # op.alter_column('sales', 'sale_day',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'sale_day',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('expiry')
    # ### end Alembic commands ###
