"""updated inventory table

Revision ID: 901e895816f9
Revises: 9e93d6a61aaf
Create Date: 2025-01-10 04:58:12.604703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '901e895816f9'
down_revision: Union[str, None] = '9e93d6a61aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('is_discounted', sa.Boolean(), nullable=False))
    op.add_column('inventory', sa.Column('discount_percentage', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'discount_percentage')
    op.drop_column('inventory', 'is_discounted')
    # ### end Alembic commands ###
