"""added vendor_id field

Revision ID: a80e230c9f7b
Revises: 6f22cc912e45
Create Date: 2025-01-09 22:05:22.609915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a80e230c9f7b'
down_revision: Union[str, None] = '6f22cc912e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('products', sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'vendor_id')
    op.drop_column('inventory', 'vendor_id')
    # ### end Alembic commands ###
